### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by joepaquette** [tangdrew/fhir-ts#7]
After successfully completing `npm install` followed by `npm run bootstrap`, I executed `npm run build`. It failed with `error TS1149: File name '/mnt/c/DevGitHub/fhir-ts/packages/primitives/src/R4/base64binary.ts' differs from already included file name '/mnt/c/DevGitHub/fhir-ts/packages/primitives/src/R4/base64Binary.ts' only in casing.`.

StdOut:
[fhir-ts-build-failure.txt](https://github.com/tangdrew/fhir-ts/files/2884713/fhir-ts-build-failure.txt)

Running `npm run build:typescript` did succeed. Re-running `npm run build` after that still failed as before.

I'm not familiar with using yarn or lerna, so any recommendations would be appreciated.

**Comment by tangdrew** [comment]
Looks like the issue is in the primitives package. Have you pulled down the latest changes on master? I changed the name to `base64Binary` to match what's in the FHIR spec in this [release](https://github.com/tangdrew/fhir-ts/blob/master/packages/primitives/CHANGELOG.md#021-2019-02-17). Thanks for letting me know about issues you run into, I'll try to take this feedback into account when I get around to writing documentation on how to contribute!

**Comment by joepaquette** [comment]
I pulled down the latest from master but still had the same problem. It turns out that the file name must match the export name. So, you need to rename `base64binary.ts` to `base64Binary.ts`. I did that locally and the build succeeded.

**Comment by tangdrew** [comment]
Ah ok, it turns out you have to explicitly rename files using `git mv` when you're just changing the capitalization for git to notice the changes. Should be updated now!
